# Generated by Django 4.2.1 on 2023-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('ratings', models.IntegerField()),
                ('date_posted', models.DateField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
